name: build and push
on: pull_request
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Declare commit sha id
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_RW_USER }}
        password: ${{ secrets.DOCKER_HUB_RW_SECRET }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: src/Dockerfile
        push: true
        tags: kemaldev/dotnet-test:${{ steps.vars.outputs.sha_short }}