name: build and push
on: pull_request
env:
  GIT_HASH: $(git rev-parse --short "$GITHUB_SHA")
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_RW_USER }}
        password: ${{ secrets.DOCKER_HUB_RW_SECRET }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: src/Dockerfile
        push: true
        tags: kemaldev/dotnet-test:$GIT_HASH
