name: build and push
on: pull_request
permissions:
  checks: write # needed for dorny/test-reporter@v1 to work properly.
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET Core SDK 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.100'
    - name: dotnet restore
      run: dotnet restore src/TestApp/TestApp.csproj
    - name: dotnet build
      run: dotnet build src/TestApp/TestApp.csproj --no-restore
    - name: dotnet test
      run: dotnet test src/TestApp.UnitTests/TestApp.UnitTests.csproj --logger "trx;logfilename=test-results.trx" --results-directory . # --no-restore option causing tests to not run for some reason
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: dotnet tests
        path: './test-results.trx'
        reporter: dotnet-trx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ AZ_REGISTRY_USER }}
        password: ${{ AZ_REGISTRY_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: src/Dockerfile
        push: true
        tags: kemaldev.azurecr.io/dotnet-test:pr-${{ github.event.number }} # pr number is tag here