name: build and push
on: pull_request
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET Core SDK 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'
    - name: dotnet restore
      run: dotnet restore src/TestApp/TestApp.csproj
    - name: dotnet build
      run: dotnet build src/TestApp/TestApp.csproj --no-restore
    - name: dotnet test
      run: dotnet test src/TestApp.UnitTests/TestApp.UnitTests.csproj --no-restore --logger "trx;logfilename=test-results.trx"
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: dotnet tests
        path: test-results.trx
        reporter: dotnet-trx
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_RW_USER }}
        password: ${{ secrets.DOCKER_HUB_RW_SECRET }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        file: src/Dockerfile
        push: true
        tags: kemaldev/dotnet-test:${{ steps.vars.outputs.sha_short }}